import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Leaf, Award, Globe, ShieldCheck, Flame, BarChart3, ChevronDown, ChevronUp, Users, Heart } from 'lucide-react';

const Landing = () => {
  const [activeFaq, setActiveFaq] = useState(null);

  const toggleFaq = (idx) => {
    setActiveFaq(activeFaq === idx ? null : idx);
  };

  const faqData = [
    {
      q: "What is a carbon footprint?",
      a: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our individual actions, commutes, utility heating/cooling usage, diet patterns, and recycling habits."
    },
    {
      q: "How does EcoTrack calculate my footprint?",
      a: "EcoTrack runs an automated carbon calculator engine utilizing standardized EPA and IPCC emissions coefficients. We multiply your logged distances, servings, kilowatt-hours, and trash kilograms by verified multipliers to compile exact kg CO2e metrics."
    },
    {
      q: "What are the benefits of setting a carbon budget?",
      a: "A carbon budget establishes a maximum monthly limit for your emissions. EcoTrack monitors your daily logs against this budget to keep you conscious of consumption limits and warns you when you cross threshold levels."
    },
    {
      q: "How does the AI recommendation engine work?",
      a: "Our system gathers your weekly averages and feeds them to our recommendation algorithms. If you configure a Gemini API key, it generates custom markdown summaries; otherwise, it falls back to localized heuristic matrices to target your highest category."
    }
  ];

  return (
    <div className="app-container" style={{ minHeight: '100vh', background: 'var(--bg-dark)' }}>
      {/* LANDING HEADER NAVIGATION */}
      <header style={{ borderBottom: '1px solid var(--glass-border)', background: 'var(--glass-surface)' }}>
        <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '1rem 1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '1.5rem' }}>
            <Leaf style={{ color: 'var(--primary-emerald)' }} />
            <span>Eco<span style={{ color: 'var(--primary-emerald)' }}>Track</span></span>
          </div>
          <div style={{ display: 'flex', gap: '1rem' }}>
            <Link to="/login" className="btn-secondary" style={{ padding: '0.5rem 1rem', fontSize: '0.9rem' }}>
              Log In
            </Link>
            <Link to="/register" className="btn-primary" style={{ padding: '0.5rem 1.2rem', fontSize: '0.9rem', width: 'auto' }}>
              Get Started
            </Link>
          </div>
        </div>
      </header>

      {/* HERO SECTION */}
      <section className="landing-hero">
        <div>
          <div className="landing-tagline">Track. Analyze. Offset.</div>
          <h1 className="landing-title">
            Take Control of Your <span style={{ color: 'var(--primary-emerald)' }}>Carbon Footprint</span>
          </h1>
          <p className="landing-desc">
            Join thousands of active users monitoring residential utilities, commutes, diets, and waste. Log habits daily, track target budgets, unlock earned achievement badges, and discover personalized carbon reductions powered by AI.
          </p>
          <div className="landing-actions">
            <Link to="/register" className="btn-primary" style={{ width: 'auto', padding: '1rem 2rem' }}>
              Create Free Account
            </Link>
            <a href="#features" className="btn-secondary" style={{ padding: '1rem 2rem' }}>
              Explore Features
            </a>
          </div>
        </div>
        <div className="landing-hero-graphics">
          <div className="landing-glow-circle">
            <Leaf size={72} style={{ color: 'var(--primary-emerald)', filter: 'drop-shadow(0 0 15px var(--primary-emerald))' }} />
          </div>
        </div>
      </section>

      {/* STATISTICS COUNTER SECTION */}
      <section className="landing-stats">
        <div className="landing-stats-grid">
          <div>
            <div className="landing-stat-num">14,250 kg</div>
            <div className="landing-stat-label">Carbon Reduced</div>
          </div>
          <div>
            <div className="landing-stat-num">950+</div>
            <div className="landing-stat-label">Active Climbers</div>
          </div>
          <div>
            <div className="landing-stat-num">480+</div>
            <div className="landing-stat-label">Trees Saved Equivalent</div>
          </div>
          <div>
            <div className="landing-stat-num">87%</div>
            <div className="landing-stat-label">User Success Rate</div>
          </div>
        </div>
      </section>

      {/* FEATURES MATRIX SECTION */}
      <section id="features" className="landing-features">
        <h2 className="landing-section-title">Engineered for a Greener Tomorrow</h2>
        <div className="landing-features-grid">
          
          <div className="glass-card landing-feature-card">
            <div className="landing-feature-icon">
              <Flame size={24} />
            </div>
            <h3>Emissions Calculator</h3>
            <p style={{ color: 'var(--slate-text-muted)', fontSize: '0.9rem', lineHeight: '1.5' }}>
              Translate transport kilometers, dietary serving sizes, and appliance wattages into exact kilograms of greenhouse gas equivalents ($CO_2e$).
            </p>
          </div>

          <div className="glass-card landing-feature-card">
            <div className="landing-feature-icon">
              <BarChart3 size={24} />
            </div>
            <h3>Historical Analytics</h3>
            <p style={{ color: 'var(--slate-text-muted)', fontSize: '0.9rem', lineHeight: '1.5' }}>
              Unpack monthly trendlines, categorical pies, and budget performance bars powered by interactive Recharts visual plot graphs.
            </p>
          </div>

          <div className="glass-card landing-feature-card">
            <div className="landing-feature-icon">
              <Award size={24} />
            </div>
            <h3>Gamified Achievements</h3>
            <p style={{ color: 'var(--slate-text-muted)', fontSize: '0.9rem', lineHeight: '1.5' }}>
              Earn digital collection badges like "Green Commuter" and "Eco Explorer" by logging plant-based meals and recycling household trash.
            </p>
          </div>

          <div className="glass-card landing-feature-card">
            <div className="landing-feature-icon">
              <Globe size={24} />
            </div>
            <h3>Offset Contributions</h3>
            <p style={{ color: 'var(--slate-text-muted)', fontSize: '0.9rem', lineHeight: '1.5' }}>
              Understand offset equivalencies and calculate the exact tree counts required to neutralize your logged monthly carbon emission outputs.
            </p>
          </div>

        </div>
      </section>

      {/* FAQ SECTION */}
      <section className="landing-faq">
        <h2 className="landing-section-title">Frequently Asked Questions</h2>
        <div className="faq-list">
          {faqData.map((faq, idx) => (
            <div key={idx} className="faq-item">
              <button className="faq-question" onClick={() => toggleFaq(idx)}>
                <span>{faq.q}</span>
                {activeFaq === idx ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
              </button>
              {activeFaq === idx && (
                <div className="faq-answer">
                  <p>{faq.a}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* LANDING FOOTER */}
      <footer className="landing-footer">
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
          <Users size={16} />
          <span>EcoTrack Sustainability Project</span>
        </div>
        <p style={{ fontSize: '0.8rem' }}>
          Built with <Heart size={12} style={{ color: 'var(--danger-rose)', display: 'inline' }} /> for hackathons, placement portfolios, and B.Tech CSE vivas.
        </p>
        <p style={{ fontSize: '0.75rem', marginTop: '0.5rem' }}>
          &copy; {new Date().getFullYear()} EcoTrack Awareness Platform. All rights reserved.
        </p>
      </footer>
    </div>
  );
};

export default Landing;
